/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import config.koneksi;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class AdminPage extends javax.swing.JFrame {

    private CardLayout cardLayout;
    Profile p;
    static DefaultTableModel m, mod_p;
    
    Color defaultColor = new Color(42, 50, 38); // Warna latar gelap
    Color activeColor = new Color(62,66,62); // Warna pilihan (highlight)
    Color hoverColor = new Color(62,66,62);
    
    public AdminPage() {
        initComponents();
        
        settingTable();  
        viewData("");
        cardLayout = (CardLayout)(pnlCard.getLayout());
        viewDataProduk(""); 
    }
    
    public AdminPage(Profile P) {
        initComponents();
        
        
        this.p = P;
        labelUser.setText(p.getFullname() + "(" + p.getLevel() + ")");
        cardLayout = (CardLayout)(pnlCard.getLayout());
        settingTable();  
        viewData("");
        viewDataProduk(""); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        pnlDataUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDataProduk = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlDataTransaksi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        pnlCard = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnTambahUser = new javax.swing.JButton();
        btnUbahData = new javax.swing.JButton();
        btnHapusData = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        pnlCard2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnTambahProduk = new javax.swing.JButton();
        btnUbahProduk = new javax.swing.JButton();
        btnHapusproduk = new javax.swing.JButton();
        btnRefreshProduk = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDataProduk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(42, 50, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDataUser.setBackground(new java.awt.Color(42, 50, 38));
        pnlDataUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDataUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDataUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDataUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDataUserMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-group-28.png"))); // NOI18N
        jLabel1.setText("     Data User");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlDataUserLayout = new javax.swing.GroupLayout(pnlDataUser);
        pnlDataUser.setLayout(pnlDataUserLayout);
        pnlDataUserLayout.setHorizontalGroup(
            pnlDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataUserLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlDataUserLayout.setVerticalGroup(
            pnlDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pnlDataUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 50));

        pnlDataProduk.setBackground(new java.awt.Color(42, 50, 38));
        pnlDataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDataProdukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDataProdukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDataProdukMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDataProdukMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-product-28.png"))); // NOI18N
        jLabel2.setText("     Data Produk");

        javax.swing.GroupLayout pnlDataProdukLayout = new javax.swing.GroupLayout(pnlDataProduk);
        pnlDataProduk.setLayout(pnlDataProdukLayout);
        pnlDataProdukLayout.setHorizontalGroup(
            pnlDataProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataProdukLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
        );
        pnlDataProdukLayout.setVerticalGroup(
            pnlDataProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pnlDataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 50));

        pnlDataTransaksi.setBackground(new java.awt.Color(42, 50, 38));
        pnlDataTransaksi.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlDataTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDataTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDataTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDataTransaksiMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-transaction-list-28.png"))); // NOI18N
        jLabel3.setText("      Data Transaksi");

        javax.swing.GroupLayout pnlDataTransaksiLayout = new javax.swing.GroupLayout(pnlDataTransaksi);
        pnlDataTransaksi.setLayout(pnlDataTransaksiLayout);
        pnlDataTransaksiLayout.setHorizontalGroup(
            pnlDataTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataTransaksiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDataTransaksiLayout.setVerticalGroup(
            pnlDataTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataTransaksiLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(pnlDataTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 50));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-26.png"))); // NOI18N
        jLabel4.setText("Admin");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        labelUser.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 40));

        btnkeluar.setBackground(new java.awt.Color(42, 50, 38));
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkeluarMousePressed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-30.png"))); // NOI18N
        btnLogout.setText("     Keluar");

        javax.swing.GroupLayout btnkeluarLayout = new javax.swing.GroupLayout(btnkeluar);
        btnkeluar.setLayout(btnkeluarLayout);
        btnkeluarLayout.setHorizontalGroup(
            btnkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnkeluarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        btnkeluarLayout.setVerticalGroup(
            btnkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 50));

        splitPane.setLeftComponent(jPanel2);

        pnlCard.setLayout(new java.awt.CardLayout());

        pnlCard1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(42, 50, 38));

        btnTambahUser.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnTambahUser.setForeground(new java.awt.Color(42, 50, 38));
        btnTambahUser.setText("Tambah");
        btnTambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahUserActionPerformed(evt);
            }
        });

        btnUbahData.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnUbahData.setForeground(new java.awt.Color(42, 50, 38));
        btnUbahData.setText("Ubah");
        btnUbahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDataActionPerformed(evt);
            }
        });

        btnHapusData.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnHapusData.setForeground(new java.awt.Color(42, 50, 38));
        btnHapusData.setText("Hapus");
        btnHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDataActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(42, 50, 38));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(42, 50, 38));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-24.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 30));

        txtKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyActionPerformed(evt);
            }
        });
        jPanel3.add(txtKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(btnTambahUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbahData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUbahData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pnlCard1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Nama Lengkap", "Username", "Password", "level"
            }
        ));
        jScrollPane3.setViewportView(tbluser);

        pnlCard1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnlCard.add(pnlCard1, "pnlCard1");

        pnlCard2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(42, 50, 38));

        btnTambahProduk.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnTambahProduk.setForeground(new java.awt.Color(42, 50, 38));
        btnTambahProduk.setText("Tambah");
        btnTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdukActionPerformed(evt);
            }
        });

        btnUbahProduk.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnUbahProduk.setForeground(new java.awt.Color(42, 50, 38));
        btnUbahProduk.setText("Ubah");
        btnUbahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahProdukActionPerformed(evt);
            }
        });

        btnHapusproduk.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnHapusproduk.setForeground(new java.awt.Color(42, 50, 38));
        btnHapusproduk.setText("Hapus");
        btnHapusproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusprodukActionPerformed(evt);
            }
        });

        btnRefreshProduk.setFont(new java.awt.Font("JetBrains Mono", 0, 13)); // NOI18N
        btnRefreshProduk.setForeground(new java.awt.Color(42, 50, 38));
        btnRefreshProduk.setText("Refresh");
        btnRefreshProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshProdukActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(42, 50, 38));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-24.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(btnTambahProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbahProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusproduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefreshProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapusproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUbahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pnlCard2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        tblDataProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id", "Kode Produk", "Nama Produk", "Gambar Produk", "Kategori", "Supplier", "Harga Jual", "Harga Beli", "Stok"
            }
        ));
        jScrollPane4.setViewportView(tblDataProduk);

        pnlCard2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pnlCard.add(pnlCard2, "pnlCard2");

        splitPane.setRightComponent(pnlCard);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    splitPane.setEnabled(false); // Menonaktifkan kemampuan menggeser divider
    splitPane.setDividerSize(0); // Menyembunyikan divider (opsional)

    }//GEN-LAST:event_formWindowOpened

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        viewData("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void pnlDataUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataUserMousePressed
        cardLayout.show(pnlCard, "pnlCard1");
    }//GEN-LAST:event_pnlDataUserMousePressed

    private void btnRefreshProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshProdukActionPerformed
        viewDataProduk(""); 
    }//GEN-LAST:event_btnRefreshProdukActionPerformed

    private void btnkeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMousePressed
        int option = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin keluar?", "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    // Jika pengguna memilih Yes
    if (option == JOptionPane.YES_OPTION) {
        // Tampilkan form login dan sembunyikan form utama
        LoginPage login = new LoginPage();
        login.setVisible(true); // Tampilkan LoginForm
        this.dispose(); // Tutup MainForm
    }
    }//GEN-LAST:event_btnkeluarMousePressed

    private void txtKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyActionPerformed
        String key = txtKey.getText();
        String where = "WHERE "
        + "fullname LIKE '%" + key + "%' OR "
        + "username LIKE '%" + key + "%' OR "
        + "password LIKE '%" + key + "%' OR "
        + "level LIKE '%" + key + "%'";
        viewData(where);
    }//GEN-LAST:event_txtKeyActionPerformed

    private void btnHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDataActionPerformed
        int n = tbluser.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(tbluser.getValueAt(n, 1).toString());
            String fullname = tbluser.getValueAt(n, 2).toString();

            int opsi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data "+fullname+"?",
                "Hapus Data",
                JOptionPane.YES_NO_OPTION);
            if(opsi == 0){
                String Q = "DELETE FROM users "
                + "WHERE id="+id;

                try {
                    Connection K = koneksi.Go();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewData("");
                    JOptionPane.showMessageDialog(this, "Data "+fullname+" telah terhapus");
                } catch (SQLException e) {
                }
            }

        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnHapusDataActionPerformed

    private void pnlDataProdukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataProdukMousePressed
        cardLayout.show(pnlCard, "pnlCard2");
    }//GEN-LAST:event_pnlDataProdukMousePressed

    private void pnlDataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataUserMouseClicked
        setActivePanel(pnlDataUser);
    }//GEN-LAST:event_pnlDataUserMouseClicked

    private void pnlDataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataProdukMouseClicked
        setActivePanel(pnlDataProduk);
    }//GEN-LAST:event_pnlDataProdukMouseClicked

    private void pnlDataTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataTransaksiMouseClicked
        setActivePanel(pnlDataTransaksi);
    }//GEN-LAST:event_pnlDataTransaksiMouseClicked

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
        setActivePanel(btnkeluar);
    }//GEN-LAST:event_btnkeluarMouseClicked

    private void pnlDataUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataUserMouseEntered
        if (pnlDataUser.getBackground() != activeColor) { // Ubah warna jika tidak aktif
                pnlDataUser.setBackground(hoverColor);
            }
    }//GEN-LAST:event_pnlDataUserMouseEntered

    private void pnlDataProdukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataProdukMouseEntered
        if (pnlDataProduk.getBackground() != activeColor) { // Ubah warna jika tidak aktif
                pnlDataProduk.setBackground(hoverColor);
            }
    }//GEN-LAST:event_pnlDataProdukMouseEntered

    private void pnlDataTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataTransaksiMouseEntered
        if (pnlDataTransaksi.getBackground() != activeColor) { // Ubah warna jika tidak aktif
                pnlDataTransaksi.setBackground(hoverColor);
            }
    }//GEN-LAST:event_pnlDataTransaksiMouseEntered

    private void btnkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseEntered
        if (btnkeluar.getBackground() != activeColor) { // Ubah warna jika tidak aktif
               btnkeluar.setBackground(hoverColor);
            }
    }//GEN-LAST:event_btnkeluarMouseEntered

    private void pnlDataUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataUserMouseExited
        if (pnlDataUser.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
                pnlDataUser.setBackground(defaultColor);
        }
    }//GEN-LAST:event_pnlDataUserMouseExited

    private void pnlDataProdukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataProdukMouseExited
        if (pnlDataProduk.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
                pnlDataProduk.setBackground(defaultColor);
        }
    }//GEN-LAST:event_pnlDataProdukMouseExited

    private void pnlDataTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDataTransaksiMouseExited
        if (pnlDataTransaksi.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
                pnlDataTransaksi.setBackground(defaultColor);
        }
    }//GEN-LAST:event_pnlDataTransaksiMouseExited

    private void btnkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseExited
        if (btnkeluar.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
                btnkeluar.setBackground(defaultColor);
        }
    }//GEN-LAST:event_btnkeluarMouseExited

    private void btnUbahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDataActionPerformed
       int n = tbluser.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(tbluser.getValueAt(n, 1).toString());
            String fullname = tbluser.getValueAt(n, 2).toString();
            String username = tbluser.getValueAt(n, 3).toString();
            String password = tbluser.getValueAt(n, 4).toString();
            String level = tbluser.getValueAt(n, 5).toString();
            UbahData U = new UbahData(this, true);
            U.setIdUser(id);
            U.setFullname(fullname);
            U.setUsername(username);
            U.setPassword(password);
            U.setLevel(level);
            U.setVisible(true);

        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnUbahDataActionPerformed

    private void btnTambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahUserActionPerformed
        TambahData T = new TambahData(this, true);
        T.setVisible(true);
    }//GEN-LAST:event_btnTambahUserActionPerformed

    private void btnTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdukActionPerformed
        TambahProduk TP = new TambahProduk(this, true);
        TP.setVisible(true); 
    }//GEN-LAST:event_btnTambahProdukActionPerformed

    private void btnHapusprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusprodukActionPerformed
        int n = tblDataProduk.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(tblDataProduk.getValueAt(n, 1).toString());
            String kode = tblDataProduk.getValueAt(n, 2).toString() + " - " + tblDataProduk.getValueAt(n, 3).toString();
            
            int opsi = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin menghapus data "+kode+"?", 
                    "Hapus Data", 
                    JOptionPane.YES_NO_OPTION);
            if(opsi == 0){
                String Q = "DELETE FROM produk "
                        + "WHERE id="+id;
                
                try {
                    Connection K = koneksi.Go();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewDataProduk(""); 
                    JOptionPane.showMessageDialog(this, "Data "+kode+" telah terhapus");
                } catch (SQLException e) {
                }
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnHapusprodukActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String key = jTextField2.getText().trim();
        if (!key.isEmpty()) {
            viewDataProduk(key);
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnUbahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahProdukActionPerformed
        int n = tblDataProduk.getSelectedRow();
        if(n != -1){
            UbahProduk U = new UbahProduk(this, true);
            U.setId(Integer.parseInt(tblDataProduk.getValueAt(n, 1).toString()));
            U.setKode(tblDataProduk.getValueAt(n, 2).toString());
            U.setNama(tblDataProduk.getValueAt(n, 3).toString());
            U.setGambar(tblDataProduk.getValueAt(n, 4).toString());
            U.setKategori(tblDataProduk.getValueAt(n, 5).toString());
            U.setSuplier(tblDataProduk.getValueAt(n, 6).toString());
            U.setHargaJual(Double.parseDouble(tblDataProduk.getValueAt(n, 7).toString()));
            U.setHargaBeli(Double.parseDouble(tblDataProduk.getValueAt(n, 8).toString()));
            U.setStok(Integer.parseInt(tblDataProduk.getValueAt(n, 9).toString()));
            U.setVisible(true); 
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnUbahProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusData;
    private javax.swing.JButton btnHapusproduk;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshProduk;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.JButton btnTambahUser;
    private javax.swing.JButton btnUbahData;
    private javax.swing.JButton btnUbahProduk;
    private javax.swing.JPanel btnkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlDataProduk;
    private javax.swing.JPanel pnlDataTransaksi;
    private javax.swing.JPanel pnlDataUser;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTable tblDataProduk;
    private javax.swing.JTable tbluser;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables

    public static void viewData(String where) {
        try {
            //kode kita
            for (int i = m.getRowCount()-1; i >=0; i--) {
                m.removeRow(i);
            }

            Connection K = koneksi.Go();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM users " + where;
//            System.out.println(Q);
            ResultSet R = S.executeQuery(Q);
            int no = 1;
            while (R.next()) {
                int id = R.getInt("id");
                String fullname = R.getString("fullname");
                String username = R.getString("username");
                String password = R.getString("password");
                String level = R.getString("level");

                Object[] D = {no, id, fullname, username, password, level};
                m.addRow(D);

                no++;
            }
        } catch (SQLException e) {
            //error handling
        }
    }
    
    public static void viewDataProduk(String where) {
        try {
            for (int i = mod_p.getRowCount()-1; i >=0; i--){
                mod_p.removeRow(i);
            }
            
            Connection K = koneksi.Go(); 
            Statement S = K.createStatement();
             String Q = "SELECT * FROM products " + where;

            ResultSet R = S.executeQuery(Q);
            int no = 1;
            while (R.next()){
                int id = R.getInt("id");
                String p_code = R.getString("product_code");
                String p_name = R.getString("product_name");
                String p_image = R.getString("product_image");
                String p_category  = R.getString("product_category");
                String p_supplier = R.getString("product_supplier");
                String p_price_s = R.getString("product_price_s");
                String p_price_b = R.getString("product_price_s");
                String p_stock = R.getString("product_stock");

                Object[] D = {
                    no, id, p_code,p_name, p_image, 
                    p_category, p_supplier, p_price_s, p_price_b, p_stock};
                mod_p.addRow(D);

            no++;
        }
        
        functions.saveLog("Sukses menampilkan data produk"); 
    } catch (SQLException e) {
        // Penanganan error
        functions.saveLog("Gagal menampilkan data produk. " + e.getMessage()); 
    }
    }    
    private void settingTable() {
        m = (DefaultTableModel) tbluser.getModel();        
        tbluser.getColumnModel().getColumn(0).setMinWidth(50);
        tbluser.getColumnModel().getColumn(0).setMaxWidth(70);

        tbluser.getColumnModel().getColumn(1).setMinWidth(0);
        tbluser.getColumnModel().getColumn(1).setMaxWidth(0);

        tbluser.getColumnModel().getColumn(2).setMinWidth(350);
        tbluser.getColumnModel().getColumn(2).setMaxWidth(500);
        
        mod_p = (DefaultTableModel) tblDataProduk.getModel();        
        tblDataProduk.getColumnModel().getColumn(0).setMinWidth(50);
        tblDataProduk.getColumnModel().getColumn(0).setMaxWidth(70);

        tblDataProduk.getColumnModel().getColumn(1).setMinWidth(0);
        tblDataProduk.getColumnModel().getColumn(1).setMaxWidth(0); 
    }
    
    
    private void setActivePanel(JPanel activePanel) {
    // Reset semua panel ke warna default
    pnlDataUser.setBackground(defaultColor);
    pnlDataProduk.setBackground(defaultColor);
    pnlDataTransaksi.setBackground(defaultColor);
    btnkeluar.setBackground(defaultColor);

    // Set warna panel yang diklik menjadi warna pilihan
    activePanel.setBackground(activeColor);
}
}
