/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import config.koneksi;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author fadil
 */
public class Owner extends javax.swing.JFrame {

    CardLayout cardLayout;
    Profile p;
    DefaultTableModel tableModel;
    Color defaultColor = new Color(42, 50, 38); // Warna latar gelap
    Color activeColor = new Color(62, 66, 62); // Warna pilihan (highlight)
    Color hoverColor = new Color(62, 66, 62);

    public Owner() {
        initComponents();
        cardLayout = (CardLayout) (Cards.getLayout());
    }

    public Owner(Profile P) {
        initComponents();
        cardLayout = (CardLayout) (Cards.getLayout());
        this.p = P;
        lblRole.setText(p.getLevel());
        lblUser.setText(p.getFullname());
        updateProdukTerjual();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLaporanRiwayat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLaporanKeuangan1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPembelian = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Cards = new javax.swing.JPanel();
        card2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabelProdukTerjual = new javax.swing.JLabel();
        jDateChooserSampai = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserDari = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        card3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserTerlarisDari = new com.toedter.calendar.JDateChooser();
        jDateChooserTerlarisSampai = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTerlaris = new javax.swing.JTable();
        card4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooserPendapatanDari = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jDateChooserPendapatanSampai = new com.toedter.calendar.JDateChooser();
        jLabelJumlahPendapatan = new javax.swing.JLabel();
        card5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooserGrafikDari = new com.toedter.calendar.JDateChooser();
        jDateChooserGrafikSampai = new com.toedter.calendar.JDateChooser();
        jPanelGrafik = new javax.swing.JPanel();
        card6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jDateChooserRankSampai = new com.toedter.calendar.JDateChooser();
        jDateChooserRankDari = new com.toedter.calendar.JDateChooser();
        jTableRank = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(42, 50, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setBackground(new java.awt.Color(42, 50, 38));
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKeluarMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-30.png"))); // NOI18N
        jLabel3.setText("     Keluar");

        javax.swing.GroupLayout btnKeluarLayout = new javax.swing.GroupLayout(btnKeluar);
        btnKeluar.setLayout(btnKeluarLayout);
        btnKeluarLayout.setHorizontalGroup(
            btnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKeluarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnKeluarLayout.setVerticalGroup(
            btnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKeluarLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 190, -1));

        btnLaporanRiwayat.setBackground(new java.awt.Color(42, 50, 38));
        btnLaporanRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanRiwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanRiwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanRiwayatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaporanRiwayatMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-transaction-list-28.png"))); // NOI18N
        jLabel2.setText("     Jumlah Pendapatan");

        javax.swing.GroupLayout btnLaporanRiwayatLayout = new javax.swing.GroupLayout(btnLaporanRiwayat);
        btnLaporanRiwayat.setLayout(btnLaporanRiwayatLayout);
        btnLaporanRiwayatLayout.setHorizontalGroup(
            btnLaporanRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanRiwayatLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnLaporanRiwayatLayout.setVerticalGroup(
            btnLaporanRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanRiwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(btnLaporanRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, 260, 50));

        btnLaporanKeuangan1.setBackground(new java.awt.Color(42, 50, 38));
        btnLaporanKeuangan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanKeuangan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanKeuangan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanKeuangan1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaporanKeuangan1MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-product-28.png"))); // NOI18N
        jLabel4.setText("     Produk Terlaris");

        javax.swing.GroupLayout btnLaporanKeuangan1Layout = new javax.swing.GroupLayout(btnLaporanKeuangan1);
        btnLaporanKeuangan1.setLayout(btnLaporanKeuangan1Layout);
        btnLaporanKeuangan1Layout.setHorizontalGroup(
            btnLaporanKeuangan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanKeuangan1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btnLaporanKeuangan1Layout.setVerticalGroup(
            btnLaporanKeuangan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanKeuangan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(btnLaporanKeuangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 50));

        btnPembelian.setBackground(new java.awt.Color(42, 50, 38));
        btnPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPembelianMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPembelianMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-purchase-28.png"))); // NOI18N
        jLabel1.setText("     Produk Terjual");

        javax.swing.GroupLayout btnPembelianLayout = new javax.swing.GroupLayout(btnPembelian);
        btnPembelian.setLayout(btnPembelianLayout);
        btnPembelianLayout.setHorizontalGroup(
            btnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPembelianLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        btnPembelianLayout.setVerticalGroup(
            btnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPembelianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.add(btnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 260, 40));

        lblUser.setFont(new java.awt.Font("JetBrains Mono", 0, 21)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("jLabel4");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, -1));

        lblRole.setFont(new java.awt.Font("JetBrains Mono", 0, 21)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-26.png"))); // NOI18N
        lblRole.setText("jLabel4");
        jPanel2.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, -1));

        jPanel5.setBackground(new java.awt.Color(42, 50, 38));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 110));

        jPanel10.setBackground(new java.awt.Color(42, 50, 38));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel10MousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-profitability-28.png"))); // NOI18N
        jLabel14.setText("     Grafik Penjualan");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 40));

        jPanel11.setBackground(new java.awt.Color(42, 50, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel11MousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-group-28.png"))); // NOI18N
        jLabel15.setText("     Kasir Rank");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 260, 30));

        jSplitPane1.setLeftComponent(jPanel2);

        Cards.setLayout(new java.awt.CardLayout());

        card2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(42, 50, 38));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(42, 50, 38));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel14.setBackground(new java.awt.Color(42, 50, 38));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProdukTerjual.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabelProdukTerjual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProdukTerjual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProdukTerjual.setText("0");
        jPanel14.add(jLabelProdukTerjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 440, -1));

        jDateChooserSampai.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jDateChooserSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserSampaiPropertyChange(evt);
            }
        });
        jPanel14.add(jDateChooserSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 191, 364, 45));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sampai:");
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, -1, -1));

        jDateChooserDari.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jDateChooserDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDariPropertyChange(evt);
            }
        });
        jPanel14.add(jDateChooserDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 128, 362, 45));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dari:");
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 129, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Produk Terjual");
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 47, 6);
        jPanel4.add(jPanel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(104, 106, 131, 88);
        jPanel3.add(jPanel4, gridBagConstraints);

        card2.add(jPanel3, java.awt.BorderLayout.CENTER);

        Cards.add(card2, "card2");

        card3.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(42, 50, 38));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-profitability-28.png"))); // NOI18N
        jLabel8.setText("Produk Terlaris");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 57, 0, 0);
        jPanel8.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dari:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 181, 0, 0);
        jPanel8.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sampai:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 157, 0, 0);
        jPanel8.add(jLabel10, gridBagConstraints);

        jDateChooserTerlarisDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserTerlarisDariPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 298;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 123);
        jPanel8.add(jDateChooserTerlarisDari, gridBagConstraints);

        jDateChooserTerlarisSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserTerlarisSampaiPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 298;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 30, 123);
        jPanel8.add(jDateChooserTerlarisSampai, gridBagConstraints);

        card3.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jTableTerlaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nomor", "Jumlah Barang", "Nama Barang"
            }
        ));
        jScrollPane1.setViewportView(jTableTerlaris);

        card3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Cards.add(card3, "card3");

        card4.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(42, 50, 38));

        jPanel7.setBackground(new java.awt.Color(42, 50, 38));

        jPanel9.setBackground(new java.awt.Color(42, 50, 38));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jumlah Pendapatan");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dari:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 119, 50));

        jDateChooserPendapatanDari.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jDateChooserPendapatanDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserPendapatanDariPropertyChange(evt);
            }
        });
        jPanel9.add(jDateChooserPendapatanDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 293, 40));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sampai:");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, -1));

        jDateChooserPendapatanSampai.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jDateChooserPendapatanSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserPendapatanSampaiPropertyChange(evt);
            }
        });
        jPanel9.add(jDateChooserPendapatanSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 293, 40));

        jLabelJumlahPendapatan.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabelJumlahPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJumlahPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJumlahPendapatan.setText("Rp. XXX.XXX.XXX");
        jPanel9.add(jLabelJumlahPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        card4.add(jPanel6, java.awt.BorderLayout.CENTER);

        Cards.add(card4, "card4");

        card5.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(42, 50, 38));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel16.setFont(new java.awt.Font("JetBrains Mono", 0, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Grafik Penjualan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 15, 0, 0);
        jPanel12.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dari:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 232, 0, 0);
        jPanel12.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Sampai:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 206, 0, 0);
        jPanel12.add(jLabel18, gridBagConstraints);

        jDateChooserGrafikDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserGrafikDariPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 18, 0, 190);
        jPanel12.add(jDateChooserGrafikDari, gridBagConstraints);

        jDateChooserGrafikSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserGrafikSampaiPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 32, 190);
        jPanel12.add(jDateChooserGrafikSampai, gridBagConstraints);

        card5.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanelGrafik.setLayout(new java.awt.BorderLayout());
        card5.add(jPanelGrafik, java.awt.BorderLayout.CENTER);

        Cards.add(card5, "card5");

        card6.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(42, 50, 38));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel19.setFont(new java.awt.Font("JetBrains Mono", 0, 21)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Kasir Rank");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 33, 0, 0);
        jPanel13.add(jLabel19, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Dari:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 234, 0, 0);
        jPanel13.add(jLabel20, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Sampai:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 234, 12, 0);
        jPanel13.add(jLabel21, gridBagConstraints);

        jDateChooserRankSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserRankSampaiPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 12, 231);
        jPanel13.add(jDateChooserRankSampai, gridBagConstraints);

        jDateChooserRankDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserRankDariPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 231);
        jPanel13.add(jDateChooserRankDari, gridBagConstraints);

        card6.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jTableRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama", "Jumlah transaksi", "Jumlah Barang"
            }
        ));
        card6.add(jTableRank, java.awt.BorderLayout.CENTER);

        Cards.add(card6, "card6");

        jSplitPane1.setRightComponent(Cards);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        setActivePanel(btnKeluar);
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseEntered
        if (btnKeluar.getBackground() != activeColor) { // Ubah warna jika tidak aktif
            btnKeluar.setBackground(hoverColor);
        }
    }//GEN-LAST:event_btnKeluarMouseEntered

    private void btnKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseExited
        if (btnKeluar.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
            btnKeluar.setBackground(defaultColor);
        }
    }//GEN-LAST:event_btnKeluarMouseExited

    private void btnKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMousePressed
        int option = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?", "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // Jika pengguna memilih Yes
        if (option == JOptionPane.YES_OPTION) {
            // Tampilkan form login dan sembunyikan form utama
            LoginPage login = new LoginPage();
            login.setVisible(true); // Tampilkan LoginForm
            this.dispose(); // Tutup MainForm
        }
    }//GEN-LAST:event_btnKeluarMousePressed

    private void btnLaporanRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanRiwayatMouseClicked
        setActivePanel(btnLaporanRiwayat);
    }//GEN-LAST:event_btnLaporanRiwayatMouseClicked

    private void btnLaporanRiwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanRiwayatMouseEntered
        if (btnLaporanRiwayat.getBackground() != activeColor) { // Ubah warna jika tidak aktif
            btnLaporanRiwayat.setBackground(hoverColor);
        }
    }//GEN-LAST:event_btnLaporanRiwayatMouseEntered

    private void btnLaporanRiwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanRiwayatMouseExited
        if (btnLaporanRiwayat.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
            btnLaporanRiwayat.setBackground(defaultColor);
        }
    }//GEN-LAST:event_btnLaporanRiwayatMouseExited

    private void btnLaporanRiwayatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanRiwayatMousePressed
        cardLayout.show(Cards, "card4");
    }//GEN-LAST:event_btnLaporanRiwayatMousePressed

    private void btnLaporanKeuangan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanKeuangan1MouseClicked
        setActivePanel(btnLaporanKeuangan1);
    }//GEN-LAST:event_btnLaporanKeuangan1MouseClicked

    private void btnLaporanKeuangan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanKeuangan1MouseEntered
        if (btnLaporanKeuangan1.getBackground() != activeColor) { // Ubah warna jika tidak aktif
            btnLaporanKeuangan1.setBackground(hoverColor);
        }
    }//GEN-LAST:event_btnLaporanKeuangan1MouseEntered

    private void btnLaporanKeuangan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanKeuangan1MouseExited
        if (btnLaporanKeuangan1.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
            btnLaporanKeuangan1.setBackground(defaultColor);
        }
    }//GEN-LAST:event_btnLaporanKeuangan1MouseExited

    private void btnLaporanKeuangan1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanKeuangan1MousePressed
        cardLayout.show(Cards, "card3");
        System.out.println("card3");
    }//GEN-LAST:event_btnLaporanKeuangan1MousePressed

    private void btnPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembelianMouseClicked
        setActivePanel(btnPembelian);
    }//GEN-LAST:event_btnPembelianMouseClicked

    private void btnPembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembelianMouseEntered
        if (btnPembelian.getBackground() != activeColor) { // Ubah warna jika tidak aktif
            btnPembelian.setBackground(hoverColor);
        }
    }//GEN-LAST:event_btnPembelianMouseEntered

    private void btnPembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembelianMouseExited
        if (btnPembelian.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
            btnPembelian.setBackground(defaultColor);
        }
    }//GEN-LAST:event_btnPembelianMouseExited

    private void btnPembelianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembelianMousePressed
        cardLayout.show(Cards, "card2");
        System.out.println("Switching to pnlCardPembelian");
    }//GEN-LAST:event_btnPembelianMousePressed

    private void jDateChooserDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDariPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateProdukTerjual();
        }
    }//GEN-LAST:event_jDateChooserDariPropertyChange

    private void jDateChooserSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserSampaiPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateProdukTerjual();
        }
    }//GEN-LAST:event_jDateChooserSampaiPropertyChange

    private void jDateChooserTerlarisDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserTerlarisDariPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateTerlaris();
        }
    }//GEN-LAST:event_jDateChooserTerlarisDariPropertyChange

    private void jDateChooserTerlarisSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserTerlarisSampaiPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateTerlaris();
        }
    }//GEN-LAST:event_jDateChooserTerlarisSampaiPropertyChange

    private void jDateChooserPendapatanDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserPendapatanDariPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updatePendapatan();
        }
    }//GEN-LAST:event_jDateChooserPendapatanDariPropertyChange

    private void jDateChooserPendapatanSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserPendapatanSampaiPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updatePendapatan();
        }
    }//GEN-LAST:event_jDateChooserPendapatanSampaiPropertyChange

    private void jDateChooserGrafikDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserGrafikDariPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateGrafik();
        }
    }//GEN-LAST:event_jDateChooserGrafikDariPropertyChange

    private void jDateChooserGrafikSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserGrafikSampaiPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateGrafik();
        }
    }//GEN-LAST:event_jDateChooserGrafikSampaiPropertyChange

    private void jPanel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MousePressed
        cardLayout.show(Cards, "card5");
    }//GEN-LAST:event_jPanel10MousePressed

    private void jPanel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MousePressed
        cardLayout.show(Cards, "card6");
    }//GEN-LAST:event_jPanel11MousePressed

    private void jDateChooserRankSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserRankSampaiPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateRank();
        }
    }//GEN-LAST:event_jDateChooserRankSampaiPropertyChange

    private void jDateChooserRankDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserRankDariPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            updateRank();
        }
    }//GEN-LAST:event_jDateChooserRankDariPropertyChange

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        setActivePanel(jPanel10);

    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        setActivePanel(jPanel11);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        if (jPanel10.getBackground() != activeColor) { // Ubah warna jika tidak aktif
            jPanel10.setBackground(hoverColor);
        }
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        if (jPanel11.getBackground() != activeColor) { // Ubah warna jika tidak aktif
            jPanel11.setBackground(hoverColor);
        }
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        if (jPanel10.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
            jPanel10.setBackground(defaultColor);
        }
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        if (jPanel11.getBackground() != activeColor) { // Kembali ke warna default jika tidak aktif
            jPanel11.setBackground(defaultColor);
        }    }//GEN-LAST:event_jPanel11MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JPanel btnKeluar;
    private javax.swing.JPanel btnLaporanKeuangan1;
    private javax.swing.JPanel btnLaporanRiwayat;
    private javax.swing.JPanel btnPembelian;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel card4;
    private javax.swing.JPanel card5;
    private javax.swing.JPanel card6;
    private com.toedter.calendar.JDateChooser jDateChooserDari;
    private com.toedter.calendar.JDateChooser jDateChooserGrafikDari;
    private com.toedter.calendar.JDateChooser jDateChooserGrafikSampai;
    private com.toedter.calendar.JDateChooser jDateChooserPendapatanDari;
    private com.toedter.calendar.JDateChooser jDateChooserPendapatanSampai;
    private com.toedter.calendar.JDateChooser jDateChooserRankDari;
    private com.toedter.calendar.JDateChooser jDateChooserRankSampai;
    private com.toedter.calendar.JDateChooser jDateChooserSampai;
    private com.toedter.calendar.JDateChooser jDateChooserTerlarisDari;
    private com.toedter.calendar.JDateChooser jDateChooserTerlarisSampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJumlahPendapatan;
    private javax.swing.JLabel jLabelProdukTerjual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelGrafik;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableRank;
    private javax.swing.JTable jTableTerlaris;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    private void setActivePanel(JPanel activePanel) {
        // Reset semua panel ke warna default
        btnPembelian.setBackground(defaultColor);
        btnLaporanRiwayat.setBackground(defaultColor);
        btnLaporanKeuangan1.setBackground(defaultColor);
        btnKeluar.setBackground(defaultColor);

        // Set warna panel yang diklik menjadi warna pilihan
        activePanel.setBackground(activeColor);
    }

    private void updateProdukTerjual() {
        // Get the selected dates from the date choosers
        Date dari = jDateChooserDari.getDate();
        Date sampai = jDateChooserSampai.getDate();

        // Check if dates are selected
        if (dari == null || sampai == null) {
            jLabelProdukTerjual.setText("Please select both dates.");
            return;
        }

        // Format the dates to SQL format
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariString = sdf.format(dari);
        String sampaiString = sdf.format(sampai);

        // SQL query to count products sold in the specified date range
        String query = "SELECT SUM(qty) AS total_terjual FROM transaction_detail "
                + "JOIN `transaction` ON transaction_detail.id_transaction = `transaction`.id "
                + "WHERE `transaction`.tanggal BETWEEN ? AND ?";

        try (Connection conn = config.koneksi.Go(); // Assuming your connection class is named 'koneksi'
                 PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, dariString);
            pstmt.setString(2, sampaiString);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                int totalTerjual = rs.getInt("total_terjual");
                jLabelProdukTerjual.setText(String.valueOf(totalTerjual));
            } else {
                jLabelProdukTerjual.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
            jLabelProdukTerjual.setText("Error: " + e.getMessage());
        }
    }

    private void updateTerlaris() {
        Date dari = jDateChooserTerlarisDari.getDate();
        Date sampai = jDateChooserTerlarisSampai.getDate();

        if (dari == null || sampai == null) {
            // Clear the table if dates are not selected
            DefaultTableModel model = (DefaultTableModel) jTableTerlaris.getModel();
            model.setRowCount(0);
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariString = sdf.format(dari);
        String sampaiString = sdf.format(sampai);

        String query = "SELECT p.id, SUM(td.qty) AS total_qty, p.product_name "
                + "FROM transaction_detail td "
                + "JOIN `transaction` t ON td.id_transaction = t.id "
                + "JOIN products p ON td.id_product = p.id "
                + "WHERE t.tanggal BETWEEN ? AND ? "
                + "GROUP BY p.id, p.product_name "
                + "ORDER BY total_qty DESC";

        try (Connection conn = config.koneksi.Go(); PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, dariString);
            pstmt.setString(2, sampaiString);

            ResultSet rs = pstmt.executeQuery();

            // Clear the table before adding new data
            DefaultTableModel model = (DefaultTableModel) jTableTerlaris.getModel();
            model.setRowCount(0);

            int rowNumber = 1; // Initialize row number
            while (rs.next()) {
                int id = rs.getInt("id");
                int totalQty = rs.getInt("total_qty");
                String productName = rs.getString("product_name");
                model.addRow(new Object[]{rowNumber++, totalQty, productName}); // Add row number
            }
        } catch (Exception e) {
            e.printStackTrace();
            // Optionally, you can show an error message to the user
        }
    }

    private void updatePendapatan() {
        Date dari = jDateChooserPendapatanDari.getDate();
        Date sampai = jDateChooserPendapatanSampai.getDate();

        if (dari == null || sampai == null) {
            jLabelJumlahPendapatan.setText("0");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariString = sdf.format(dari);
        String sampaiString = sdf.format(sampai);

        String query = "SELECT SUM(td.price) AS total_pendapatan "
                + "FROM transaction_detail td "
                + "JOIN `transaction` t ON td.id_transaction = t.id "
                + "WHERE t.tanggal BETWEEN ? AND ?";

        try (Connection conn = config.koneksi.Go(); PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, dariString);
            pstmt.setString(2, sampaiString);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                double totalPendapatan = rs.getDouble("total_pendapatan");
                // Format the total revenue in Rupiah
                NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
                jLabelJumlahPendapatan.setText(formatRupiah.format(totalPendapatan));
            } else {
                jLabelJumlahPendapatan.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
            jLabelJumlahPendapatan.setText("Error: " + e.getMessage());
        }
    }
    // Method to update the sales chart

    private void updateGrafik() {
        Date dari = jDateChooserGrafikDari.getDate();
        Date sampai = jDateChooserGrafikSampai.getDate();

        if (dari == null || sampai == null) {
            jPanelGrafik.removeAll(); // Clear the panel if dates are not selected
            jPanelGrafik.revalidate();
            jPanelGrafik.repaint();
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariString = sdf.format(dari);
        String sampaiString = sdf.format(sampai);

        String query = "SELECT t.tanggal, SUM(td.price) AS total_penjualan "
                + "FROM transaction_detail td "
                + "JOIN `transaction` t ON td.id_transaction = t.id "
                + "WHERE t.tanggal BETWEEN ? AND ? "
                + "GROUP BY t.tanggal "
                + "ORDER BY t.tanggal";

        try (Connection conn = config.koneksi.Go(); PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, dariString);
            pstmt.setString(2, sampaiString);

            ResultSet rs = pstmt.executeQuery();

            // Create dataset for the chart
            CategoryDataset dataset = createDataset(rs);

            // Create the chart
            JFreeChart chart = ChartFactory.createBarChart(
                    "Grafik Penjualan", // Chart title
                    "Tanggal", // X-axis label
                    "Total Penjualan (Rp)", // Y-axis label
                    dataset // Dataset
            );

            // Create a ChartPanel and add it to the jPanelGrafik
            ChartPanel chartPanel = new ChartPanel(chart);
            jPanelGrafik.removeAll(); // Clear previous chart
            jPanelGrafik.add(chartPanel);
            jPanelGrafik.revalidate();
            jPanelGrafik.repaint();
        } catch (Exception e) {
            e.printStackTrace();
            // Optionally, you can display an error message in the panel or log it
        }
    }

/// Method to create dataset from ResultSet
    private CategoryDataset createDataset(ResultSet rs) throws SQLException {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Iterate through the ResultSet
        while (rs.next()) {
            // Get the date and total sales from the ResultSet
            Date date = rs.getDate("tanggal");
            double totalPenjualan = rs.getDouble("total_penjualan");

            // Format the date to a string for the dataset
            String formattedDate = new SimpleDateFormat("dd-MM-yyyy").format(date);

            // Add the value to the dataset
            dataset.addValue(totalPenjualan, "Penjualan", formattedDate);
        }

        return dataset;
    }

    private void updateRank() {
        Date dari = jDateChooserRankDari.getDate();
        Date sampai = jDateChooserRankSampai.getDate();

        // Check if both dates are selected
        if (dari == null || sampai == null) {
            DefaultTableModel model = (DefaultTableModel) jTableRank.getModel();
            model.setRowCount(0);
            return;
        }

        // Format the dates to SQL format
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariString = sdf.format(dari);
        String sampaiString = sdf.format(sampai);

        // SQL query to get the rank of cashiers
        String query = "SELECT u.fullname AS kasir, COUNT(t.id) AS jumlah_transaksi, SUM(td.qty) AS jumlah_produk "
                + "FROM users u "
                + "JOIN `transaction` t ON u.id = t.cashier_id "
                + // Use cashier_id
                "JOIN transaction_detail td ON t.id = td.id_transaction "
                + "WHERE t.tanggal BETWEEN ? AND ? "
                + "GROUP BY u.id "
                + "ORDER BY jumlah_transaksi DESC";

        try (Connection conn = config.koneksi.Go(); PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, dariString);
            pstmt.setString(2, sampaiString);

            ResultSet rs = pstmt.executeQuery();

            // Clear the table before adding new data
            DefaultTableModel model = (DefaultTableModel) jTableRank.getModel();
            model.setRowCount(0); // Clear previous data

            int rowNumber = 1; // Initialize row number
            while (rs.next()) {
                String kasir = rs.getString("kasir");
                int jumlahTransaksi = rs.getInt("jumlah_transaksi");
                int jumlahProduk = rs.getInt("jumlah_produk");
                model.addRow(new Object[]{rowNumber++, kasir, jumlahTransaksi, jumlahProduk}); // Add row number
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
}
